version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./django/Dockerfile.development
    working_dir: /code
    env_file:
      - .env
    volumes:
      - ./django/code:/code
    stdin_open: true
    tty: true
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: umihiko-server-v2_development
      TZ: 'Asia/Tokyo'
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./nginx/log:/var/log/nginx/
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
      - db

  pgadmin4:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin4.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  db-data:
  pgadmin-data:
