version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0

jobs:
  build-push-app:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: Gcloud Config
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: |
            set -x
            docker build -t asia.gcr.io/$GOOGLE_PROJECT_ID/app -f ./django/Dockerfile.production .
      - run:
          name: Push
          command: |
            set -x
            docker push asia.gcr.io/$GOOGLE_PROJECT_ID/app

  build-push-nginx:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: |
            set -x
            docker build -t asia.gcr.io/$GOOGLE_PROJECT_ID/nginx -f ./nginx/Dockerfile.production .
      - run:
          name: Push
          command: |
            set -x
            docker push asia.gcr.io/$GOOGLE_PROJECT_ID/nginx

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build-push-app:
          filters:
            branches:
              only:
                - main
                - circleci-test
      - build-push-nginx:
          filters:
            branches:
              only:
                - main
                - circleci-test
