version: 2.1
jobs:
  build-image:
    machine: true
    steps:
      - checkout
      - run:
          name: Build a container
          command: |
            docker build -t $CIRCLE_PROJECT_REPONAME -f django/Dockerfile.production django
            docker images
workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build-image:
          filters:
            branches:
              only: main
