version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0

jobs:
  copy-json:
    docker:
      - image: circleci/python:3.9.5
    steps:
      - checkout
      - run:
          name: Copy json
          command: |
            set -x
            sed -e "s/<PGADMIN_DEFAULT_EMAIL>/${PGADMIN_DEFAULT_EMAIL}/" \
              -e "s/<PGADMIN_DEFAULT_PASSWORD>/${PGADMIN_DEFAULT_PASSWORD}/" \
              deploy.base.json > deploy.json
      - persist_to_workspace:
          root: .
          paths:
            - deploy.json
  build-push-app:
    docker:
      - image: circleci/python:3.9.5
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build
          command: |
            set -x
            docker build -t app -f ./django/Dockerfile.production .
      - aws-cli/install
      - run:
          name: Push
          command: |
            set -x
            sudo curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
            sudo chmod +x /usr/local/bin/lightsailctl
            aws lightsail push-container-image \
              --region ap-northeast-1 \
              --service-name $CIRCLE_PROJECT_REPONAME \
              --label app \
              --image app:latest

  build-push-nginx:
    docker:
      - image: circleci/python:3.9.5
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build
          command: |
            set -x
            docker build -t nginx -f ./nginx/Dockerfile.production .
      - aws-cli/install
      - run:
          name: Push
          command: |
            set -x
            sudo curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
            sudo chmod +x /usr/local/bin/lightsailctl
            aws lightsail push-container-image \
              --region ap-northeast-1 \
              --service-name $CIRCLE_PROJECT_REPONAME \
              --label nginx \
              --image nginx:latest | \
              grep Refer | awk '{print $6}' | sed -i -e "s/\"<nginx-image>\"/$(cat)/" deploy.json

  deploy:
    docker:
      - image: circleci/python:3.9.5
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - aws-cli/install
      - run:
          name: Deploy
          command: |
            set -x
            sudo curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
            sudo chmod +x /usr/local/bin/lightsailctl
            cat deploy.json
            aws lightsail create-container-service-deployment \
              --service-name $CIRCLE_PROJECT_REPONAME \
              --cli-input-json deploy.json

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - copy-json:
          filters:
            branches:
              only:
                - main
                - circleci-test
      - build-push-app:
          requires:
            - copy-json
          filters:
            branches:
              only:
                - main
                - circleci-test
      - build-push-nginx:
          requires:
            - copy-json
          filters:
            branches:
              only:
                - main
                - circleci-test
      - deploy:
          requires:
            - build-push-app
            - build-push-nginx
          filters:
            branches:
              only:
                - main
                - circleci-test
