version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0

jobs:
  build-push-app:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build
          command: |
            set -x
            docker build -t asia.gcr.io/$CIRCLE_PROJECT_REPONAME/app -f ./django/Dockerfile.production .
      - run:
          name: Push
          command: |
            set -x
            docker push asia.gcr.io/$CIRCLE_PROJECT_REPONAME/app

  build-push-nginx:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: |
            set -x
            docker build -t asia.gcr.io/$CIRCLE_PROJECT_REPONAME/nginx -f ./nginx/Dockerfile.production .
      - run:
          name: Push
          command: |
            set -x
            docker push asia.gcr.io/$CIRCLE_PROJECT_REPONAME/nginx

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build-push-app:
          filters:
            branches:
              only:
                - main
                - circleci-test
      - build-push-nginx:
          filters:
            branches:
              only:
                - main
                - circleci-test
