version: 2.1
jobs:
  build-image:
    machine: true
    steps:
      - checkout
      - run:
          name: Build a container
          command: |
            docker login .......
            docker build --progress plain -t umihiko-server-v2 ./django/Dockerfile.production
            docker images
workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build-image:
          filters:
            branches:
              only: main
