version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0

jobs:
  make-gcp-json:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Create gcloud credential
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > gcloud.json
      - persist_to_workspace:
          root: .
          paths:
            - gcloud.json
  build-push-app:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Gcloud Config
          command: |
            gcloud auth activate-service-account --key-file gcloud.json
            gcloud auth configure-docker
      - setup_remote_docker
      - run:
          name: Build
          command: |
            set -x
            docker build -t asia.gcr.io/$GOOGLE_PROJECT_ID/app -f ./django/Dockerfile.production .
      - run:
          name: Push
          command: |
            set -x
            docker push asia.gcr.io/$GOOGLE_PROJECT_ID/app

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - make-gcp-json:
          filters:
            branches:
              only:
                - main
                - circleci-test
      - build-push-app:
          requires:
            - make-gcp-json
          filters:
            branches:
              only:
                - main
                - circleci-test
