FROM python:3.9-buster as builder
ENV PYTHONUNBUFFERED 1
WORKDIR /code
COPY ./django/requirements ./requirements
RUN pip install --upgrade pip && \
    pip install -r requirements/development.txt

FROM python:3.9-slim-buster
ENV PYTHONUNBUFFERED 1
WORKDIR /code
RUN apt-get update && \
    apt-get install -y mime-support
COPY --from=builder /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages
COPY ./django/code .
COPY ./django/umihiko-server-v2-development.json /etc
