# Generated by Django 3.2.4 on 2021-06-16 23:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0006_auto_20210617_0831"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProfileEn",
            new_name="EnglishProfile",
        ),
    ]
